include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    non_constant_identifier_names: false
    invalid_annotation_target: false
    always_use_package_imports: true
    avoid_void_async: true
    unnecessary_await_in_return: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*_model.dart'
