name: accswift
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flex_color_scheme: ^4.1.1
  flutter:
    sdk: flutter
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.2
  fluttertoast: ^8.0.8
  freezed_annotation: null
  get_it: ^7.2.0
  ionicons: ^0.1.2
  json_annotation: null
  logger: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  
dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
